<h1> Hotel Booking Prediction<h1>

***Overview of Data***:
##### The data is taken from "www.kaggle.com". The data set conatin the information such as when the booking made, length od stay, number of babies, number of adults, parking space, etc. we predict that the chance to costomer will cancel booking. if booking was cancelled denote by 1.


In [1]:
# import libraries
import numpy as np
import pandas as pd

***Load Data***

In [2]:
df = pd.read_csv(r"D:\HP\think_next\data_science\hotel_bookings.csv")
df.head().T

0             1             2  \
hotel                           Resort Hotel  Resort Hotel  Resort Hotel   
is_canceled                                0             0             0   
lead_time                                342           737             7   
arrival_date_year                       2015          2015          2015   
arrival_date_month                      July          July          July   
arrival_date_week_number                  27            27            27   
arrival_date_day_of_month                  1             1             1   
stays_in_weekend_nights                    0             0             0   
stays_in_week_nights                       0             0             1   
adults                                     2             2             1   
children                                 0.0           0.0           0.0   
babies                                     0             0             0   
meal                                      BB            BB            BB   
country                                  PRT           PRT           GBR   
market_segment                        Direct        Direct        Direct   
distribution_channel                  Direct        Direct        Direct   
is_repeated_guest                          0             0             0   
previous_cancellations                     0             0             0   
previous_bookings_not_canceled             0             0             0   
reserved_room_type                         C             C             A   
assigned_room_type                         C             C             C   
booking_changes                            3             4             0   
deposit_type                      No Deposit    No Deposit    No Deposit   
agent                                    NaN           NaN           NaN   
company                                  NaN           NaN           NaN   
days_in_waiting_list                       0             0             0   
customer_type                      Transient     Transient     Transient   
adr                                      0.0           0.0          75.0   
required_car_parking_spaces                0             0             0   
total_of_special_requests                  0             0             0   
reservation_status                 Check-Out     Check-Out     Check-Out   
reservation_status_date             7/1/2015      7/1/2015      7/2/2015   

                                           3             4  
hotel                           Resort Hotel  Resort Hotel  
is_canceled                                0             0  
lead_time                                 13            14  
arrival_date_year                       2015          2015  
arrival_date_month                      July          July  
arrival_date_week_number                  27            27  
arrival_date_day_of_month                  1             1  
stays_in_weekend_nights                    0             0  
stays_in_week_nights                       1             2  
adults                                     1             2  
children                                 0.0           0.0  
babies                                     0             0  
meal                                      BB            BB  
country                                  GBR           GBR  
market_segment                     Corporate     Online TA  
distribution_channel               Corporate         TA/TO  
is_repeated_guest                          0             0  
previous_cancellations                     0             0  
previous_bookings_not_canceled             0             0  
reserved_room_type                         A             A  
assigned_room_type                         A             A  
booking_changes                            0             0  
deposit_type                      No Deposit    No Deposit  
agent                                  304.0         240.0  
company  

***check null values***

In [3]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
company                           82137


##### ***Drop some columns (its depend on you which columns is important for your model  and which not)***

In [7]:
df.drop(['agent','company','reservation_status_date'],axis=1,inplace=True)


In [8]:
df.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           452
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car

***Fill missing value with most frequent value with respective columns***

In [9]:
df.fillna(df.mode().iloc[0],inplace=True)

***split target feature***

In [10]:
y = df.iloc[:,1]  # target feature
x = df.drop('is_canceled',axis=1)

***convert caterical columns*** For model training we need numerical columns.

In [11]:
from sklearn.preprocessing import OneHotEncoder
from  sklearn.compose import make_column_transformer

In [12]:
ct = make_column_transformer((OneHotEncoder(),['hotel','meal','distribution_channel','reservation_status','country','arrival_date_month','market_segment','deposit_type','customer_type', 'reserved_room_type','assigned_room_type' ]), remainder = 'passthrough')

In [13]:
x = ct.fit_transform(x).toarray()

***split data train test***

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_trian,y_test = train_test_split(x,y,test_size=0.25,random_state=4)

***standerdization of feature***

In [16]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =  sc.fit_transform(x_test)

***feature selection(there is too many feature) throught PCA***

In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 100)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_

***Train model with LogisticRegression***

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=4, max_iter=1000)
lr.fit(x_train,y_trian)

LogisticRegression(max_iter=1000, random_state=4)

In [19]:
y_pred = lr.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[15792,     4],
       [    2,  6051]], dtype=int64)

In [21]:
from sklearn.svm import SVC

***Train model with SVC***

In [22]:
clf = SVC(kernel='linear')
clf.fit(x_train,y_trian)

SVC(kernel='linear')

In [23]:
y_pred_svc = clf.predict(x_test)

In [24]:
cm_svm = confusion_matrix(y_test,y_pred_svc)
cm_svm

array([[15792,     4],
       [    4,  6049]], dtype=int64)

***Train model with RandomForest***

In [25]:
from sklearn.ensemble import RandomForestClassifier
rg = RandomForestClassifier(n_estimators=1000,random_state=4)
rg.fit(x_train,y_trian)

RandomForestClassifier(n_estimators=1000, random_state=4)

In [26]:
y_pred_rf = rg.predict(x_test)

In [27]:
cm_rf =  confusion_matrix(y_test,y_pred_rf)
cm_rf

array([[15789,     7],
       [   52,  6001]], dtype=int64)

***compare the accuracy of all model's***

In [28]:
from sklearn.metrics import accuracy_score

Accuracy of LogisticRegression

In [29]:
ac_log = accuracy_score(y_test,y_pred)
ac_log

0.999725387889606

Accuracy of SVM

In [30]:
ac_svm =  accuracy_score(y_test,y_pred_svc)
ac_svm

0.9996338505194746

Accuracy of RandomForest

In [31]:
ac_rf =  accuracy_score(y_test,y_pred_rf)
ac_rf

0.997299647581125

***Conclusion***
#### The model SVC gives the best accuracy that is 99.99%